import { NextRequest, NextResponse } from 'next/server'

/**
 * Pattern generation API route.
 * This demonstrates Codex working side-by-side: the mathematical pattern
 * functions were generated by Codex; GPT-5.6 handles the fashion logic.
 */
export async function POST(req: NextRequest) {
  const { bust, waist, hip, back_length, shoulder, inseam, garment_type } = await req.json()

  // Validate measurements
  const b = parseFloat(bust) || 88
  const w = parseFloat(waist) || 68
  const h = parseFloat(hip) || 94
  const bl = parseFloat(back_length) || 40
  const sh = parseFloat(shoulder) || 12
  const ins = parseFloat(inseam) || 75

  const pieces = generatePatternPieces(b, w, h, bl, sh, ins, garment_type ?? 'dress')
  const svg = piecesToSVG(pieces)
  const fabric_estimate = estimateFabricYards(pieces)

  return NextResponse.json({ pieces, svg, fabric_estimate })
}

// ── Pattern math (Codex-generated) ──────────────────────────────────────────

interface Point { x: number; y: number }
interface Piece {
  name: string
  points: Point[]
  grain: [Point, Point]
  width: number
  height: number
  labels: Record<string, Point>
}

function bodiceBack(b: number, w: number, bl: number, sh: number): Piece {
  const hb = (b + 4) / 4  // quarter bust (with 4cm ease)
  const hw = w / 4
  const ad = bl * 0.4    // armhole depth

  const points: Point[] = [
    { x: 0, y: 0 },              // A: CB neck
    { x: sh, y: 0 },             // B: shoulder
    { x: hb, y: ad },            // E: armhole
    { x: hw + (hb - hw) / 2, y: bl },  // D: side waist
    { x: 0, y: bl },             // C: CB waist
  ]
  return {
    name: 'Bodice Back',
    points,
    grain: [{ x: 0.5, y: bl * 0.2 }, { x: 0.5, y: bl * 0.8 }],
    width: hb,
    height: bl,
    labels: { 'CB Neck': { x: 0, y: 0 }, 'Shoulder': { x: sh, y: 0 }, 'CB Waist': { x: 0, y: bl } },
  }
}

function bodiceFront(b: number, w: number, bl: number, sh: number): Piece {
  const hb = (b + 4) / 4 + 0.5
  const hw = w / 4
  const ad = (bl + 1.5) * 0.4
  const dartIntake = Math.max(0, hb - hw) * 0.6

  const points: Point[] = [
    { x: 0, y: 0 },
    { x: sh - 0.5, y: 0 },
    { x: hb, y: ad },
    { x: hb, y: ad + 3 },               // dart top
    { x: hb * 0.6, y: ad * 0.8 },       // bust point
    { x: hb, y: ad + 3 + dartIntake },  // dart bottom
    { x: hw, y: bl + 1.5 },
    { x: 0, y: bl + 1.5 },
  ]
  return {
    name: 'Bodice Front',
    points,
    grain: [{ x: 0.5, y: (bl + 1.5) * 0.2 }, { x: 0.5, y: (bl + 1.5) * 0.8 }],
    width: hb,
    height: bl + 1.5,
    labels: { 'CF Neck': { x: 0, y: 0 }, 'CF Waist': { x: 0, y: bl + 1.5 } },
  }
}

function straightSkirt(w: number, h: number, length: number): Piece {
  const hw = w / 4
  const hh = h / 4
  const hipDepth = 20
  const dartIntake = Math.max(0, hh - hw)
  const dartPos = hw * 0.5

  const points: Point[] = [
    { x: 0, y: 0 },
    { x: dartPos - dartIntake / 4, y: 0 },
    { x: dartPos, y: hipDepth - 5 },     // dart tip
    { x: dartPos + dartIntake / 4, y: 0 },
    { x: hw, y: 0 },
    { x: hh, y: hipDepth },
    { x: hh, y: length },
    { x: 0, y: length },
  ]
  return {
    name: 'Straight Skirt Back',
    points,
    grain: [{ x: hh * 0.5, y: length * 0.1 }, { x: hh * 0.5, y: length * 0.9 }],
    width: hh,
    height: length,
    labels: { 'CB Waist': { x: 0, y: 0 }, 'CB Hem': { x: 0, y: length } },
  }
}

function generatePatternPieces(
  b: number, w: number, h: number, bl: number,
  sh: number, ins: number, type: string
): Piece[] {
  const pieces: Piece[] = [bodiceBack(b, w, bl, sh), bodiceFront(b, w, bl, sh)]
  if (type === 'dress' || type === 'skirt') {
    pieces.push(straightSkirt(w, h, type === 'dress' ? 65 : 55))
  }
  return pieces
}

// ── SVG renderer ─────────────────────────────────────────────────────────────

function piecesToSVG(pieces: Piece[], scale = 5, padding = 30): string {
  let xOffset = padding
  const yOffset = padding
  let maxH = 0
  const groups: string[] = []

  for (const piece of pieces) {
    const bb = boundingBox(piece.points)
    const w = (bb.maxX - bb.minX) * scale
    const h = (bb.maxY - bb.minY) * scale

    const tx = (x: number) => ((x - bb.minX) * scale + xOffset).toFixed(1)
    const ty = (y: number) => ((y - bb.minY) * scale + yOffset).toFixed(1)

    const pathD = piece.points
      .map((p, i) => `${i === 0 ? 'M' : 'L'} ${tx(p.x)} ${ty(p.y)}`)
      .join(' ') + ' Z'

    const grainLine = piece.grain
      ? `<line x1="${tx(piece.grain[0].x)}" y1="${ty(piece.grain[0].y)}" x2="${tx(piece.grain[1].x)}" y2="${ty(piece.grain[1].y)}" stroke="#e85f00" stroke-width="1.5" stroke-dasharray="4,2" marker-end="url(#arrow)"/>`
      : ''

    const labelEls = Object.entries(piece.labels).map(([label, pt]) =>
      `<text x="${tx(pt.x)}" y="${(Number(ty(pt.y)) - 4).toFixed(1)}" font-size="7" fill="#0066ff" text-anchor="middle">${label}</text>`
    ).join('\n    ')

    const pieceNameX = (xOffset + w / 2).toFixed(1)
    const pieceNameY = (yOffset + h / 2).toFixed(1)

    groups.push(`  <g id="${piece.name.replace(/\s+/g, '-').toLowerCase()}">
    <path d="${pathD}" fill="#fef3e8" stroke="#1a1a2e" stroke-width="1.5"/>
    ${grainLine}
    ${labelEls}
    <text x="${pieceNameX}" y="${pieceNameY}" font-size="9" fill="#1d3557" text-anchor="middle" font-weight="bold">${piece.name}</text>
  </g>`)

    maxH = Math.max(maxH, h)
    xOffset += w + padding
  }

  const totalW = xOffset + padding
  const totalH = maxH + yOffset + padding

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${totalW.toFixed(0)}" height="${totalH.toFixed(0)}" viewBox="0 0 ${totalW.toFixed(0)} ${totalH.toFixed(0)}">
  <defs>
    <marker id="arrow" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto">
      <path d="M0,0 L6,3 L0,6 Z" fill="#e85f00"/>
    </marker>
  </defs>
  <rect width="${totalW.toFixed(0)}" height="${totalH.toFixed(0)}" fill="#f8f9fa"/>
${groups.join('\n')}
</svg>`
}

function boundingBox(pts: Point[]): { minX: number; minY: number; maxX: number; maxY: number } {
  return {
    minX: Math.min(...pts.map(p => p.x)),
    minY: Math.min(...pts.map(p => p.y)),
    maxX: Math.max(...pts.map(p => p.x)),
    maxY: Math.max(...pts.map(p => p.y)),
  }
}

function estimateFabricYards(pieces: Piece[]): Record<string, number | string> {
  const totalArea = pieces.reduce((sum, p) => sum + p.width * p.height, 0)
  const lengthCm = Math.ceil((totalArea * 2 * 1.15) / 114 / 10) * 10
  return {
    total_cm: lengthCm,
    total_metres: Math.round(lengthCm / 100 * 100) / 100,
    total_yards: Math.round(lengthCm / 91.44 * 100) / 100,
    fabric_width_cm: 114,
    pieces_count: pieces.length,
    note: 'Add 10% for print matching',
  }
}
