'use client'

import { useState } from 'react'
import { Navbar } from '@/components/Navbar'
import { OfflineIndicator } from '@/components/OfflineIndicator'
import toast from 'react-hot-toast'
import { Palette, Loader2, Download, Ruler } from 'lucide-react'

interface PatternResult {
  svg: string
  fabric_estimate: Record<string, number | string>
  pieces: { name: string; width: number; height: number }[]
}

const DEFAULT_MEASUREMENTS = {
  bust: '88', waist: '68', hip: '94',
  back_length: '40', shoulder: '12', inseam: '75',
}

export default function DesignPage() {
  const [measurements, setMeasurements] = useState(DEFAULT_MEASUREMENTS)
  const [garmentType, setGarmentType] = useState('dress')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<PatternResult | null>(null)

  const generate = async () => {
    setLoading(true)
    try {
      const resp = await fetch('/api/pattern', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...measurements, garment_type: garmentType }),
      })
      const data = await resp.json()
      setResult(data)
      toast.success('Pattern generated!')
    } catch {
      toast.error('Failed to generate pattern')
    } finally {
      setLoading(false)
    }
  }

  const downloadSVG = () => {
    if (!result?.svg) return
    const blob = new Blob([result.svg], { type: 'image/svg+xml' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `aku-pattern-${garmentType}.svg`
    a.click()
    URL.revokeObjectURL(url)
  }

  const measurementFields = [
    { key: 'bust', label: 'Bust (cm)', hint: 'Full bust circumference' },
    { key: 'waist', label: 'Waist (cm)', hint: 'Natural waist' },
    { key: 'hip', label: 'Hip (cm)', hint: 'Full hip circumference' },
    { key: 'back_length', label: 'Back Length (cm)', hint: 'Nape to waist' },
    { key: 'shoulder', label: 'Shoulder (cm)', hint: 'Shoulder width (across back)' },
    { key: 'inseam', label: 'Inseam (cm)', hint: 'For trousers only' },
  ] as const

  return (
    <>
      <Navbar />
      <OfflineIndicator />

      <main className="pt-20 pb-20 px-4 max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-purple-600 rounded-xl flex items-center justify-center">
              <Palette className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">Pattern Generator</h1>
              <p className="text-dark-400 text-sm">Codex-generated pattern math · SVG output · Professional quality</p>
            </div>
          </div>
          <div className="bg-purple-600/10 border border-purple-600/20 rounded-xl px-4 py-3 text-sm text-purple-300 mt-4">
            💡 <strong>Codex side-by-side:</strong> The pattern math functions powering this tool were generated by Codex —
            precisely calculating bodice blocks, dart intake, armhole curves, and skirt panels from your measurements.
          </div>
        </div>

        <div className="grid lg:grid-cols-[380px,1fr] gap-6">
          {/* Left: inputs */}
          <div className="space-y-4">
            <div className="bg-dark-800 border border-dark-700 rounded-2xl p-5">
              <h2 className="font-semibold mb-4 flex items-center gap-2">
                <Ruler className="w-4 h-4 text-purple-400" />
                Measurements
              </h2>

              {/* Garment type */}
              <div className="mb-4">
                <label className="text-xs text-dark-400 mb-2 block">Garment Type</label>
                <div className="grid grid-cols-3 gap-2">
                  {['dress', 'skirt', 'bodice'].map(type => (
                    <button
                      key={type}
                      onClick={() => setGarmentType(type)}
                      className={`py-2 rounded-lg text-sm font-medium transition-colors capitalize ${garmentType === type ? 'bg-purple-600 text-white' : 'bg-dark-700 text-dark-300 hover:bg-dark-600'}`}
                    >
                      {type}
                    </button>
                  ))}
                </div>
              </div>

              {/* Measurement inputs */}
              <div className="space-y-3">
                {measurementFields.map(({ key, label, hint }) => (
                  <div key={key}>
                    <label className="text-xs text-dark-400 mb-1 block">{label}</label>
                    <input
                      type="number"
                      value={measurements[key]}
                      onChange={e => setMeasurements(prev => ({ ...prev, [key]: e.target.value }))}
                      className="w-full bg-dark-700 border border-dark-600 focus:border-purple-600 rounded-lg px-3 py-2 text-sm focus:outline-none transition-colors"
                      placeholder={hint}
                    />
                    <p className="text-xs text-dark-600 mt-0.5">{hint}</p>
                  </div>
                ))}
              </div>

              <button
                onClick={generate}
                disabled={loading}
                className="mt-5 w-full flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white font-semibold py-3 rounded-xl transition-colors"
              >
                {loading ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating…</> : <><Palette className="w-4 h-4" /> Generate Pattern</>}
              </button>
            </div>

            {/* Fabric estimate */}
            {result?.fabric_estimate && (
              <div className="bg-dark-800 border border-dark-700 rounded-2xl p-5 animate-slide-up">
                <h3 className="font-medium mb-3 text-sm">Fabric Estimate</h3>
                <div className="space-y-2">
                  {Object.entries(result.fabric_estimate).map(([k, v]) => (
                    <div key={k} className="flex justify-between text-sm">
                      <span className="text-dark-400 capitalize">{k.replace(/_/g, ' ')}</span>
                      <span className="font-medium">{String(v)}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Right: SVG output */}
          <div>
            {result ? (
              <div className="animate-slide-up space-y-4">
                {/* Piece info */}
                <div className="flex items-center justify-between">
                  <div className="flex gap-2">
                    {result.pieces.map(p => (
                      <span key={p.name} className="text-xs bg-dark-800 border border-dark-700 px-3 py-1 rounded-full text-dark-300">
                        {p.name}
                      </span>
                    ))}
                  </div>
                  <button
                    onClick={downloadSVG}
                    className="flex items-center gap-1.5 text-sm bg-dark-800 hover:bg-dark-700 border border-dark-700 px-3 py-1.5 rounded-lg transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download SVG
                  </button>
                </div>

                {/* SVG display */}
                <div className="pattern-svg-container">
                  <div
                    dangerouslySetInnerHTML={{ __html: result.svg }}
                    className="w-full overflow-x-auto"
                  />
                </div>

                <div className="text-xs text-dark-500 text-center">
                  Pattern pieces at scale · Seam allowance: 1.5 cm · All measurements in cm
                  <br />
                  <span className="text-purple-400">🔴 Red dashed line = grain line direction</span>
                </div>
              </div>
            ) : (
              <div className="h-full min-h-[400px] bg-dark-800 border border-dark-700 border-dashed rounded-2xl flex flex-col items-center justify-center text-dark-500 gap-4">
                <Palette className="w-12 h-12 opacity-30" />
                <div className="text-center">
                  <p className="font-medium">Pattern preview will appear here</p>
                  <p className="text-sm">Enter measurements and click Generate</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  )
}
