name: Auto-add Issues to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'bug') ||
      contains(github.event.issue.labels.*.name, 'feature') ||
      contains(github.event.issue.labels.*.name, 'chore')
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/oumar-code/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
